# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uart.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_Button.setGeometry(QtCore.QRect(10, 240, 75, 24))
        self.connect_Button.setObjectName("connect_Button")
        self.baud_List = QtWidgets.QComboBox(self.centralwidget)
        self.baud_List.setGeometry(QtCore.QRect(100, 240, 69, 22))
        self.baud_List.setObjectName("baud_List")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 220, 49, 16))
        self.label.setObjectName("label")
        self.port_List = QtWidgets.QComboBox(self.centralwidget)
        self.port_List.setGeometry(QtCore.QRect(100, 300, 69, 22))
        self.port_List.setObjectName("port_List")
        self.disconnect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect_Button.setGeometry(QtCore.QRect(10, 300, 81, 24))
        self.disconnect_Button.setObjectName("disconnect_Button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 280, 49, 16))
        self.label_2.setObjectName("label_2")
        self.send_Button = QtWidgets.QPushButton(self.centralwidget)
        self.send_Button.setGeometry(QtCore.QRect(710, 410, 75, 24))
        self.send_Button.setObjectName("send_Button")
        self.clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_Button.setGeometry(QtCore.QRect(700, 180, 75, 24))
        self.clear_Button.setObjectName("clear_Button")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 210, 601, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.send_Text = QtWidgets.QTextEdit(self.centralwidget)
        self.send_Text.setGeometry(QtCore.QRect(180, 410, 521, 31))
        self.send_Text.setObjectName("send_Text")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 211, 161))
        self.label_3.setStyleSheet("image: url(:/myImage/geladeira.jpg)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "msp430 terminal"))
        self.connect_Button.setText(_translate("MainWindow", "CONNECT"))
        self.label.setText(_translate("MainWindow", "Baud"))
        self.disconnect_Button.setText(_translate("MainWindow", "DISCONNECT"))
        self.label_2.setText(_translate("MainWindow", "Port"))
        self.send_Button.setText(_translate("MainWindow", "SEND"))
        self.clear_Button.setText(_translate("MainWindow", "CLEAR"))
import image


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
